// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/customerio-app-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.CustomerioAppSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.CustomerioAppSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.CustomerioAppSDK, name string) (sdk.CustomerioAppEntity, error) {
	switch strings.ToLower(name) {
	case "action":
		return client.Action(nil), nil
	case "activity":
		return client.Activity(nil), nil
	case "asset":
		return client.Asset(nil), nil
	case "attribute":
		return client.Attribute(nil), nil
	case "automation":
		return client.Automation(nil), nil
	case "broadcast":
		return client.Broadcast(nil), nil
	case "campaign":
		return client.Campaign(nil), nil
	case "collection":
		return client.Collection(nil), nil
	case "content":
		return client.Content(nil), nil
	case "customer":
		return client.Customer(nil), nil
	case "data_index":
		return client.DataIndex(nil), nil
	case "delivery":
		return client.Delivery(nil), nil
	case "design_studio":
		return client.DesignStudio(nil), nil
	case "design_studio_email":
		return client.DesignStudioEmail(nil), nil
	case "email":
		return client.Email(nil), nil
	case "end":
		return client.End(nil), nil
	case "esp_suppression":
		return client.EspSuppression(nil), nil
	case "export":
		return client.Export(nil), nil
	case "import":
		return client.Import(nil), nil
	case "in_app":
		return client.InApp(nil), nil
	case "inbox_message":
		return client.InboxMessage(nil), nil
	case "info":
		return client.Info(nil), nil
	case "ip_address":
		return client.IpAddress(nil), nil
	case "language":
		return client.Language(nil), nil
	case "link":
		return client.Link(nil), nil
	case "live_notification":
		return client.LiveNotification(nil), nil
	case "message":
		return client.Message(nil), nil
	case "newsletter":
		return client.Newsletter(nil), nil
	case "newsletter_metric":
		return client.NewsletterMetric(nil), nil
	case "newsletter_variant":
		return client.NewsletterVariant(nil), nil
	case "object":
		return client.Object(nil), nil
	case "object_type":
		return client.ObjectType(nil), nil
	case "opt_out":
		return client.OptOut(nil), nil
	case "push":
		return client.Push(nil), nil
	case "relationship":
		return client.Relationship(nil), nil
	case "reporting_webhook":
		return client.ReportingWebhook(nil), nil
	case "search_suppression":
		return client.SearchSuppression(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "send_message":
		return client.SendMessage(nil), nil
	case "sender_identity":
		return client.SenderIdentity(nil), nil
	case "sms":
		return client.Sms(nil), nil
	case "snippet":
		return client.Snippet(nil), nil
	case "start":
		return client.Start(nil), nil
	case "subscription_center":
		return client.SubscriptionCenter(nil), nil
	case "subscription_channel":
		return client.SubscriptionChannel(nil), nil
	case "subscription_topic":
		return client.SubscriptionTopic(nil), nil
	case "suppression":
		return client.Suppression(nil), nil
	case "test_group":
		return client.TestGroup(nil), nil
	case "transactional":
		return client.Transactional(nil), nil
	case "trigger":
		return client.Trigger(nil), nil
	case "update":
		return client.Update(nil), nil
	case "whatsapp":
		return client.Whatsapp(nil), nil
	case "workspace":
		return client.Workspace(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
