// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/customerio-app-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"action | activity | asset | attribute | automation | broadcast | campaign | collection | content | customer | data_index | delivery | design_studio | design_studio_email | email | end | esp_suppression | export | import | in_app | inbox_message | info | ip_address | language | link | live_notification | message | newsletter | newsletter_metric | newsletter_variant | object | object_type | opt_out | push | relationship | reporting_webhook | search_suppression | segment | send_message | sender_identity | sms | snippet | start | subscription_center | subscription_channel | subscription_topic | suppression | test_group | transactional | trigger | update | whatsapp | workspace"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.CustomerioAppSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "customerio-app_list",
		Description: "List records from CustomerioApp. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "customerio-app_load",
		Description: "Load a single record from CustomerioApp. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.CustomerioAppSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.CustomerioAppSDK, name string) (sdk.CustomerioAppEntity, error) {
	switch strings.ToLower(name) {
	case "action":
		return client.Action(nil), nil
	case "activity":
		return client.Activity(nil), nil
	case "asset":
		return client.Asset(nil), nil
	case "attribute":
		return client.Attribute(nil), nil
	case "automation":
		return client.Automation(nil), nil
	case "broadcast":
		return client.Broadcast(nil), nil
	case "campaign":
		return client.Campaign(nil), nil
	case "collection":
		return client.Collection(nil), nil
	case "content":
		return client.Content(nil), nil
	case "customer":
		return client.Customer(nil), nil
	case "data_index":
		return client.DataIndex(nil), nil
	case "delivery":
		return client.Delivery(nil), nil
	case "design_studio":
		return client.DesignStudio(nil), nil
	case "design_studio_email":
		return client.DesignStudioEmail(nil), nil
	case "email":
		return client.Email(nil), nil
	case "end":
		return client.End(nil), nil
	case "esp_suppression":
		return client.EspSuppression(nil), nil
	case "export":
		return client.Export(nil), nil
	case "import":
		return client.Import(nil), nil
	case "in_app":
		return client.InApp(nil), nil
	case "inbox_message":
		return client.InboxMessage(nil), nil
	case "info":
		return client.Info(nil), nil
	case "ip_address":
		return client.IpAddress(nil), nil
	case "language":
		return client.Language(nil), nil
	case "link":
		return client.Link(nil), nil
	case "live_notification":
		return client.LiveNotification(nil), nil
	case "message":
		return client.Message(nil), nil
	case "newsletter":
		return client.Newsletter(nil), nil
	case "newsletter_metric":
		return client.NewsletterMetric(nil), nil
	case "newsletter_variant":
		return client.NewsletterVariant(nil), nil
	case "object":
		return client.Object(nil), nil
	case "object_type":
		return client.ObjectType(nil), nil
	case "opt_out":
		return client.OptOut(nil), nil
	case "push":
		return client.Push(nil), nil
	case "relationship":
		return client.Relationship(nil), nil
	case "reporting_webhook":
		return client.ReportingWebhook(nil), nil
	case "search_suppression":
		return client.SearchSuppression(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "send_message":
		return client.SendMessage(nil), nil
	case "sender_identity":
		return client.SenderIdentity(nil), nil
	case "sms":
		return client.Sms(nil), nil
	case "snippet":
		return client.Snippet(nil), nil
	case "start":
		return client.Start(nil), nil
	case "subscription_center":
		return client.SubscriptionCenter(nil), nil
	case "subscription_channel":
		return client.SubscriptionChannel(nil), nil
	case "subscription_topic":
		return client.SubscriptionTopic(nil), nil
	case "suppression":
		return client.Suppression(nil), nil
	case "test_group":
		return client.TestGroup(nil), nil
	case "transactional":
		return client.Transactional(nil), nil
	case "trigger":
		return client.Trigger(nil), nil
	case "update":
		return client.Update(nil), nil
	case "whatsapp":
		return client.Whatsapp(nil), nil
	case "workspace":
		return client.Workspace(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
