<?php
declare(strict_types=1);

// CustomerioApp SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CustomerioAppUtility::setRegistrar(function (CustomerioAppUtility $u): void {
    $u->clean = [CustomerioAppClean::class, 'call'];
    $u->done = [CustomerioAppDone::class, 'call'];
    $u->make_error = [CustomerioAppMakeError::class, 'call'];
    $u->feature_add = [CustomerioAppFeatureAdd::class, 'call'];
    $u->feature_hook = [CustomerioAppFeatureHook::class, 'call'];
    $u->feature_init = [CustomerioAppFeatureInit::class, 'call'];
    $u->fetcher = [CustomerioAppFetcher::class, 'call'];
    $u->make_fetch_def = [CustomerioAppMakeFetchDef::class, 'call'];
    $u->make_context = [CustomerioAppMakeContext::class, 'call'];
    $u->make_options = [CustomerioAppMakeOptions::class, 'call'];
    $u->make_request = [CustomerioAppMakeRequest::class, 'call'];
    $u->make_response = [CustomerioAppMakeResponse::class, 'call'];
    $u->make_result = [CustomerioAppMakeResult::class, 'call'];
    $u->make_point = [CustomerioAppMakePoint::class, 'call'];
    $u->make_spec = [CustomerioAppMakeSpec::class, 'call'];
    $u->make_url = [CustomerioAppMakeUrl::class, 'call'];
    $u->param = [CustomerioAppParam::class, 'call'];
    $u->prepare_auth = [CustomerioAppPrepareAuth::class, 'call'];
    $u->prepare_body = [CustomerioAppPrepareBody::class, 'call'];
    $u->prepare_headers = [CustomerioAppPrepareHeaders::class, 'call'];
    $u->prepare_method = [CustomerioAppPrepareMethod::class, 'call'];
    $u->prepare_params = [CustomerioAppPrepareParams::class, 'call'];
    $u->prepare_path = [CustomerioAppPreparePath::class, 'call'];
    $u->prepare_query = [CustomerioAppPrepareQuery::class, 'call'];
    $u->graphql_body = [CustomerioAppGraphql::class, 'body'];
    $u->graphql_errors = [CustomerioAppGraphql::class, 'errors'];
    $u->result_basic = [CustomerioAppResultBasic::class, 'call'];
    $u->result_body = [CustomerioAppResultBody::class, 'call'];
    $u->result_headers = [CustomerioAppResultHeaders::class, 'call'];
    $u->transform_request = [CustomerioAppTransformRequest::class, 'call'];
    $u->transform_response = [CustomerioAppTransformResponse::class, 'call'];
});
